# Jekyll!
name: Bagoes Soemargo
markdown: kramdown
title: bagoes
email: 
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  bagoes

# Build settings
theme: minima
minima:
  skin: classic
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-coffeescript
highlighter: none
kramdown:
   syntax_highlighter_opts:
      disable : true
sass:
    style: compressed
    
permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true